<?php
echo"<form method='POST' action='".$_SERVER["PHP_SELF"]."'>";
echo"<table border='0' cellspacing='0' cellpadding='0' width='100%'>";
$uname = (isset($_POST['uname']))? strip_tags($_POST['uname']) :'';
$fname = (isset($_POST['fname']))? strip_tags($_POST['fname']) :'';
$lname = (isset($_POST['lname']))? strip_tags($_POST['lname']) :'';
$email = (isset($_POST['email']))? strip_tags($_POST['email']) :'';
$box = (isset($_POST['box']))? strip_tags($_POST['box']) :'';
$zip = (isset($_POST['zip']))? strip_tags($_POST['zip']) :'';
$street = (isset($_POST['sname']))? strip_tags($_POST['sname']) :'';
$house = (isset($_POST['hnumber']))? strip_tags($_POST['hnumber']) :'';
$title = (isset($_POST['ptitle']))? strip_tags($_POST['ptitle']) :'';
$content = (isset($_POST['content']))? strip_tags($_POST['content']) :'';
$tags = (isset($_POST['tag']))? strip_tags($_POST['tag']) :'';
$tag1 = (isset($_POST['tag1']))? strip_tags($_POST['tag1']) :'';
$city = (isset($_POST['city']))? strip_tags($_POST['city']) :'';
$town = (isset($_POST['town']))? strip_tags($_POST['town']) :'';
$posted = (isset($_POST['sub']))? strip_tags($_POST['sub']) :'';
if((isset($posted)&&(!empty($posted)))&&($uname!='')&&($fname!='')&&($lname!='')&&($email!='')&&($box!='')&&($zip!='')&&($street!='')&&($house!='')
   &&($title!='')&&($content!='')&&($tags!='')&&($city!='')&&($town!=''))
{
    $connection = new Mongo();
    $db = $connection->selectDB('nicolas');
    $collection = $db->selectCollection('blog');
	$timeStamp =date('l jS \of F Y h:i:s A');
  echo"<tr>";
  echo"<td>";
  echo"You have successfully posted the article below:<br />";
  $collection->insert(array("author"=>array("username"=>"$uname","firstname"=>"$fname","lastname"=>"$lname","email"=>"$email","box"=>"$box","zip"=>"$zip","streetname"=>"$street","housenumber"=>"$house","town"=>"$town","city"=>"$city"),
  "post"=>array("title"=>"$title","content"=>"$content"),
  "tag"=>array("$tags","$tag1"),"time"=>"$timeStamp" ) );
  
  echo"$title<br />";
  echo"$content<br />";
  echo"[ $tags | $tag1 ]";
  echo"</td>";
  echo"</tr>";
}
else
{
echo"<tr>";
echo"<td colspan='2' bgcolor='gray' style='font-family:times new roman;font-size:28px'>";
echo"Upload a post:";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' width='15%' style='font-family:times new roman;font-size:18px'>";
echo"User Name";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='uname' id='uname'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' style='font-family:times new roman;font-size:18px'>";
echo"First Name";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='fname' id='fname'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' style='font-family:times new roman;font-size:18px'>";
echo"Last Name";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='lname' id='lname'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' style='font-family:times new roman;font-size:18px'>";
echo"Email";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='email' id='email'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' style='font-family:times new roman;font-size:18px'>";
echo"P.O.Box";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='box' id='box'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' style='font-family:times new roman;font-size:18px'>";
echo"Zip";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='zip' id='zip'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' style='font-family:times new roman;font-size:18px'>";
echo"Street Name";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='sname' id='sname'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' style='font-family:times new roman;font-size:18px'>";
echo"House Number";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='hnumber' id='hnumber'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1'  style='font-family:times new roman;font-size:18px'>";
echo"city";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='city' id='city'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' style='font-family:times new roman;font-size:18px'>";
echo"Town";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='town' id='town'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' style='font-family:times new roman;font-size:18px'>";
echo"Post Title";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='ptitle' id='ptitle'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' valign='top' style='font-family:times new roman;font-size:18px'>";
echo"Description";
echo"</td>";
echo"<td colspan='1'>";
echo"<textarea rows='8' cols='29' name='content' id='content'>";
echo"</textarea>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' style='font-family:times new roman;font-size:18px'>";
echo"Tag";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='tag' id='tag'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='1' style='font-family:times new roman;font-size:18px'>";
echo"Tag";
echo"</td>";
echo"<td colspan='1'>";
echo"<input type='text' name='tag1' id='tag1'>";
echo"</td>";
echo"</tr>";
echo"<tr>";
echo"<td colspan='2'>";
echo"<input type='submit' name='sub' id='sub' value='post'>";
echo"</td>";
echo"</tr>";
}
echo"</table>";
echo"</form>";
?>